; **********************************************************
; PROJE: 8086 ASSEMBLY DIJITAL SAAT UYGULAMASI
; OGRENCI ADI-SOYADI: BILAL KOCAKAPLAN
; OGRENCI BOLUMU: BILGISAYAR MUHENDISLIGI
; DERS: BLG303 MIKROISLEMCILER
; **********************************************************

.MODEL SMALL
.STACK 100H

.DATA
; --- EKRAN METINLERI ---
BASLIK        DB '=== SISTEM BILGI EKRANI ===$'
UTC_MSJ       DB 'TURKIYE SAATI (UTC+3)$'
SAAT_LABEL    DB 'SAAT  : $'
TARIH_LABEL   DB 'TARIH : $'
GUN_LABEL     DB 'GUN   : $'
CIKIS_MSJ     DB '[ Cikmak icin bir tusa basiniz ]$'

; --- GUN TABLOSU ---
G0 DB 'PAZAR     (0)$'
G1 DB 'PAZARTESI (1)$'
G2 DB 'SALI      (2)$'
G3 DB 'CARSAMBA  (3)$'
G4 DB 'PERSEMBE  (4)$'
G5 DB 'CUMA      (5)$'
G6 DB 'CUMARTESI (6)$'
GUN_ADRESLER DW G0, G1, G2, G3, G4, G5, G6

; --- VERI DEPO ALANI ---
V_SAAT DB ?
V_DAK  DB ?
V_SAN  DB ?
V_GUN  DB ?
V_AY   DB ?
V_YIL  DW ?
V_HGUN DB ?

.CODE
START:
MOV AX, @DATA
MOV DS, AX

; 1. ADIM: EKRANI MAVIYE BOYA VE HAZIRLA
MOV AH, 00H
MOV AL, 03H     ; 80x25 Metin modu
INT 10H

MOV AH, 06H
MOV AL, 0
MOV BH, 1FH     ; Mavi Arka Plan (1), Parlak Beyaz Yazi (F)
MOV CX, 0
MOV DX, 184FH
INT 10H

ANA_DONGU:
; 2. ADIM: SISTEMDEN (BIOS/DOS) ANLIK VERILERI AL
; Saat verisini cek (INT 21H, AH=2CH)
MOV AH, 2CH
INT 21H
MOV V_SAAT, CH
MOV V_DAK, CL
MOV V_SAN, DH

; Tarih verisini cek (INT 21H, AH=2AH)
MOV AH, 2AH
INT 21H
MOV V_YIL, CX   ; Bilgisayarin yil bilgisini (2026) alir
MOV V_AY, DH
MOV V_GUN, DL
MOV V_HGUN, AL

; 3. ADIM: EKRANA YAZDIRMA (MERKEZI KONUMLAR)

; Baslik
MOV DH, 8
MOV DL, 27
CALL KONUM_AYARLA
LEA DX, BASLIK
CALL METIN_BAS

; UTC Bilgisi
MOV DH, 10
MOV DL, 29
CALL KONUM_AYARLA
LEA DX, UTC_MSJ
CALL METIN_BAS

; SAAT : HH:MM:SS (Guncel sistem saati)
MOV DH, 12
MOV DL, 30
CALL KONUM_AYARLA
LEA DX, SAAT_LABEL
CALL METIN_BAS
MOV AL, V_SAAT
CALL SAYI_BAS_2
MOV DL, ':'
CALL CHAR_BAS
MOV AL, V_DAK
CALL SAYI_BAS_2
MOV DL, ':'
CALL CHAR_BAS
MOV AL, V_SAN
CALL SAYI_BAS_2

; TARIH : DD/MM/YYYY (Guncel sistem tarihi)
MOV DH, 14
MOV DL, 30
CALL KONUM_AYARLA
LEA DX, TARIH_LABEL
CALL METIN_BAS
MOV AL, V_GUN
CALL SAYI_BAS_2
MOV DL, '/'
CALL CHAR_BAS
MOV AL, V_AY
CALL SAYI_BAS_2
MOV DL, '/'
CALL CHAR_BAS
MOV AX, V_YIL
CALL YIL_BAS_4    

; GUN ADI
MOV DH, 16
MOV DL, 30
CALL KONUM_AYARLA
LEA DX, GUN_LABEL
CALL METIN_BAS
XOR BX, BX
MOV BL, V_HGUN
SHL BX, 1
MOV DX, GUN_ADRESLER[BX]
CALL METIN_BAS

; CIKIS NOTU
MOV DH, 22
MOV DL, 25
CALL KONUM_AYARLA
LEA DX, CIKIS_MSJ
CALL METIN_BAS

; 4. ADIM: KLAVYE KONTROLU (Cikis icin)
MOV AH, 01H
INT 16H
JNZ BITIR

; AKICILIK AYARI: Islemci yorulmadan saniye ve zaman akitilir
MOV CX, 0
MOV DX, 0C350H
MOV AH, 86H
INT 15H
JMP ANA_DONGU

BITIR:
MOV AH, 4CH
INT 21H

; --- YARDIMCI FONKSIYONLAR ---

KONUM_AYARLA PROC
MOV AH, 02H
MOV BH, 0
INT 10H
RET
KONUM_AYARLA ENDP

METIN_BAS PROC
MOV AH, 09H
INT 21H
RET
METIN_BAS ENDP

CHAR_BAS PROC
MOV AH, 02H
INT 21H
RET
CHAR_BAS ENDP

SAYI_BAS_2 PROC
AAM
ADD AX, 3030H
PUSH AX
MOV DL, AH
MOV AH, 02H
INT 21H
POP AX
MOV DL, AL
MOV AH, 02H
INT 21H
RET
SAYI_BAS_2 ENDP

YIL_BAS_4 PROC
; Yil kisminda DX register'i sifirlandigi icin yil artik dogru cikar.
XOR DX, DX
MOV AX, V_YIL    ; CX'ten gelen yil verisi (2026)
MOV BX, 100
DIV BX           ; AX = 20, DX = 26
PUSH DX
MOV AH, 0
CALL SAYI_BAS_2  ; 20 basar
POP AX
CALL SAYI_BAS_2  ; 26 basar
RET
YIL_BAS_4 ENDP

END START